### ISSUE TITLE
Training Code Release

### ISSUE THREAD

**Issue by zhanglaplace** [AIrocker/Real-time-human-pose-estimation-by-pytorch#1]
Thanks for your good Jobs
I test the demo on MacOS using Cpu, i can reach 2-4fps.
Can you Release the training Code？

**Comment by xuexingyu24** [comment]
Hi zhanglaplace
I didn't train the model but use the official pretrained weigths from CMU

**Comment by zhanglaplace** [comment]
@xuexingyu24 thanks。
